[tool.doxoade]
source_dir = "."
keep = [ "coverage", "pytest", "radon"]
ignore = [
    "tests/",
    "regression_tests/",
    "Canone_Test/",
    "Vers/",
    "doxoade.egg-info/",
    ".pytest_cache/",
    "pytest_temp_dir/",
    "tmp/"
]

[tool.pytest.ini_options]
addopts = "-v"
filterwarnings = [ "ignore::DeprecationWarning",]
