[tool.doxoade]
source_dir = "."
keep = [ "coverage", "pytest", "radon", "jsondiff", "pyyaml", "setuptools"]
ignore = [
    "tests/",
    "regression_tests/",
    "Canone_Test/",
    "Vers/",
    "doxoade.egg-info/",
    ".pytest_cache/",
    "pytest_temp_dir/",
    "tmp/"
]

[project]
name = "doxoade"
version = "46.0"
requires-python = ">=3.11"
dependencies = [
    "click",
    "colorama",
    "beautifulsoup4",
    "lxml",
    "cssutils",
    "esprima",
    "pyflakes",
    "toml",
    "chardet",
    "packaging",
    "pytest-cov",
    "radon",
    "coverage",
    "pytest",
    "jsondiff",
    "pyyaml",
    "setuptools",
    "pandas"
]

[project.optional-dependencies]
dashboard = ["pandas==1.5.3"]

[project.scripts]
doxoade = "doxoade.doxoade:cli"

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
packages = ["doxoade"]

[tool.pytest.ini_options]
addopts = "-v"
filterwarnings = [ "ignore::DeprecationWarning",]
